---
# create
#   configure instances to use the specified federations
- name: Configuring Instances for Federations
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port | default(omit) }}"
    log:       "{{ log_level | default(omit) }}"
    force:     "{{ force | default(omit) }}"
    action: ibmsecurity.isam.web.reverse_proxy.federation_configuration.config
    isamapi:
      instanc
  with_items: "{{ instances }}"
  when: import_personal_certs is defined
  notify:
  - Commit Changes
