- name: Configure SNMP Monitoring v1/2C
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.base.snmp_monitoring.set_v1v2
    isamapi:
      community: "{{ config_snmp_monitoring_community }}"
      port     : "{{ config_snmp_monitoring_port }}"
  notify: Commit Changes
