- name: Update Management Root Files in {{ update_management_root_instance_id }}
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.web.reverse_proxy.management_root.file.update
    isamapi:
      instance_id: "{{ update_management_root_instance_id }}"
      id         : "{{ item.id }}"
      filename   : "{{ item.filename }}"
  with_items: "{{ update_management_root_idandfilename }}"
  when: update_management_root_idandfilename is defined and update_management_root_instance_id is defined
  notify:
  - Commit Changes
