# Create a certificate database for the federated directory CAs and populate with CA
- include: cert_db.yml
# Configure the federated directory into Web Runtime ldap.conf
- include: config_fed_dir.yml
# Setup Basic User Configuration - recommended but optional
- include: config_basic_user.yml

 # Commit Runtime changes
- meta: flush_handlers
