# TCP/IP tuning as documented here: https://www-01.ibm.com/support/docview.wss?uid=swg21960611

- name: Configure TCP Ephemeral Port Range Tuning
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.base.advanced_tuning_parameters.set
    isamapi:
      key: sysctl.net.ipv4.ip_local_port_range
      value: "{{ set_tcpip_tuning_ip_local_port_range }}"
      comment: "TCP Ephemeral Port Range Tuning"
  notify:
    - Commit Changes
    - Reboot Appliance

- name: Configure TCP Time Wait Tuning
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.base.advanced_tuning_parameters.set
    isamapi:
      key: sysctl.net.ipv4.tcp_fin_timeout
      value: "{{ set_tcpip_tuning_tcp_fin_timeout }}"
      comment: "TCP Time Wait Tuning"
  notify:
    - Commit Changes
    - Reboot Appliance

- name: Configure TCP Time Wait Socket Reuse
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.base.advanced_tuning_parameters.set
    isamapi:
      key: sysctl.net.ipv4.tcp_tw_reuse
      value: "{{ set_tcpip_tuning_tcp_tw_reuse }}"
      comment: "TCP Time Wait Socket Reuse"
  notify:
    - Commit Changes
    - Reboot Appliance

- name: Configure TCP Time Wait Recycle
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.base.advanced_tuning_parameters.set
    isamapi:
      key: sysctl.net.ipv4.tcp_tw_recycle
      value: "{{ set_tcpip_tuning_tcp_tw_recycle }}"
      comment: "TCP Time Wait Recycle"
  notify:
    - Commit Changes
    - Reboot Appliance
