- name: Configure NTP
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.base.date_time.set
    isamapi:
      timeZone   : "{{ config_ntp_timeZone }}"
      ntpServers : "{{ config_ntp_ntp_servers }}"
  notify: Commit Changes
