- name: unconfigure all junctions for reverse proxy {{ unconfig_junctions_reverseproxy_id }}
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.web.reverse_proxy.junctions.delete_all
    isamapi:
      reverseproxy_id: "{{ unconfig_junctions_reverseproxy_id }}"
  when: unconfig_junctions_reverseproxy_id is defined
