- name: Import CA Certs into {{ import_ca_certs_kdb_id }}
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.base.ssl_certificates.signer_certificate.import_cert
    isamapi:
      kdb_id : "{{ import_ca_certs_kdb_id }}"
      cert   : "{{ item.cert }}"
      label  : "{{ item.label }}"
  with_items : "{{ import_ca_certs_certandlabel }}"
  when: import_ca_certs_certandlabel is defined
  notify:
  - Commit Changes
