# main task to upload jmt files
# Example:
#   jmt_files
#     - file: uploads/jmt/jmt.conf
---
- name: Upload jmt files
  isam:
    appliance: "{{ inventory_hostname }}"
    adminProxyProtocol: "{{ adminProxyProtocol | default(omit) }}"
    adminProxyHostname: "{{ adminProxyHostname | default(omit) }}"
    adminProxyPort: "{{ adminProxyPort | default(omit) }}"
    adminProxyApplianceShortName: "{{ adminProxyApplianceShortName | default(omit) }}"
    omitAdminProxy: "{{ omitAdminProxy | default(omit) }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ port | default(omit) }}"
    log:       "{{ log_level | default(omit) }}"
    force:     "{{ force | default(omit) }}"
    action: ibmsecurity.isam.web.junction_mapping.update
    isamapi:
      id: "{{ item.file | basename }}"
      jmt_config_data: "{{ lookup('file', inventory_dir + '/' + item.file) | replace('\n', '\\n') | replace('\"','\\\"') }}"
  with_items: "{{ jmt_files }}"
  when: (item.file | basename) == name
  notify: Commit Changes
