# main task to import sso key files
# Example:
#   sso_keys:
#     - file: uploads/sso_keys/failover.key
- name: Import sso key files
  isam:
    appliance: "{{ inventory_hostname }}"
    adminProxyProtocol: "{{ adminProxyProtocol | default(omit) }}"
    adminProxyHostname: "{{ adminProxyHostname | default(omit) }}"
    adminProxyPort: "{{ adminProxyPort | default(omit) }}"
    adminProxyApplianceShortName: "{{ adminProxyApplianceShortName | default(omit) }}"
    omitAdminProxy: "{{ omitAdminProxy | default(omit) }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ port | default(omit) }}"
    log:       "{{ log_level | default(omit) }}"
    force:     "{{ force | default(omit) }}"
    action: ibmsecurity.isam.web.sso_keys.import_key
    isamapi:
      id: "{{ item.file | basename }}"
      filename: "{{ inventory_dir }}/{{ item.file }}"
  when: item.file is defined and (item.file | basename) == name
  with_items: "{{ sso_keys }}"
  loop_control:
    label: "{ id: \"{{ item.file | basename }}\", filename: \"{{ inventory_dir }}/{{ item.file }}\" }"
  notify: Commit Changes