# main task to upload dynurl files
# Example:
#   dynurl_files
#     - file: uploads/dynurl/dynurl.conf
---
- name: Upload dynurl files
  isam:
    appliance: "{{ inventory_hostname }}"
    adminProxyProtocol: "{{ adminProxyProtocol | default(omit) }}"
    adminProxyHostname: "{{ adminProxyHostname | default(omit) }}"
    adminProxyPort: "{{ adminProxyPort | default(omit) }}"
    adminProxyApplianceShortName: "{{ adminProxyApplianceShortName | default(omit) }}"
    omitAdminProxy: "{{ omitAdminProxy | default(omit) }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ port | default(omit) }}"
    log:       "{{ log_level | default(omit) }}"
    force:     "{{ force | default(omit) }}"
    action: ibmsecurity.isam.web.url_mapping.import_file
    isamapi:
      id: "{{ item.file | basename }}"
      filename: "{{ inventory_dir }}/{{ item.file }}"
  with_items: "{{ dynurl_files }}"
  when: (item.file | basename) == name
  notify: Commit Changes
