- name: Deleting certificate database
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.base.ssl_certificates.certificate_databases.delete
    isamapi:
      cert_dbase_id: "{{ delete_certificate_db }}"
  notify:
    - Commit Changes