- name: Get snapshots on appliance
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action:    ibmsecurity.isam.base.snapshots.get
  register:    ret_obj

- name: Set variable for use by rest of playbook
  set_fact:
    snapshots_ret_obj: "{{ ret_obj }}"
