- name: Setup Management Authentication using AD
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.base.management_authentication.set
    isamapi:
      ldap_host:      "{{ switch_auth_ldap_host }}"
      ldap_port:      "{{ switch_auth_ldap_port }}"
      base_dn:        "{{ switch_auth_base_dn }}"
      admin_group_dn: "{{ switch_auth_admin_group_dn }}"
      enable_ssl:     "{{ switch_auth_enable_ssl }}"
      key_database:   "{{ switch_auth_key_database }}.kdb"
      cert_label:     "{{ switch_auth_cert_label | default('') }}"
      user_attribute: "{{ switch_auth_user_attribute }}"
      group_member_attribute:   "{{ switch_auth_group_member_attribute }}"
      anon_bind:      "{{ switch_auth_anon_bind }}"
      bind_dn:        "{{ switch_auth_bind_dn }}"
      bind_password:  "{{ switch_auth_bind_password }}"
  when: switch_auth_ldap_host is defined and switch_auth_ldap_port is defined
  notify: Commit Changes
