# check whether ISAM appliance LMI is ready and accept default password
- name: Check ISAM appliance for First Steps Execution
  uri:
    url: "https://{{inventory_hostname}}/lmi"
    user: admin
    password: admin
    method: GET
    return_content: yes
    force_basic_auth: yes
    status_code: 200, 403
    validate_certs: false
    HEADER_Accept: "application/json"
  check_mode: no
  register: result

- name: Assume First Steps Executed
  set_fact:
    firststeps: "skip_fs.yml"

# if default password fails we do not go through firststeps and change password
- name: Initiate logic if First Steps Required
  set_fact:
    firststeps: "firststeps.yml"
  when: result is defined and result.status == 200 and result.json.sla is defined

# Go through basic set up to accept license and set up FIPS only needed
- include: "{{firststeps}}"
  dynamic: true
