# main task to update advanced configurations
---
- name: Update advanced configurations
  isam:
    appliance: "{{ inventory_hostname }}"
    adminProxyProtocol: "{{ adminProxyProtocol | default(omit) }}"
    adminProxyHostname: "{{ adminProxyHostname | default(omit) }}"
    adminProxyPort: "{{ adminProxyPort | default(omit) }}"
    adminProxyApplianceShortName: "{{ adminProxyApplianceShortName | default(omit) }}"
    omitAdminProxy: "{{ omitAdminProxy | default(omit) }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ port | default(omit) }}"
    log:       "{{ log_level | default(omit) }}"
    force:     "{{ force | default(omit) }}"
    action: ibmsecurity.isam.aac.advanced_configuration.update
    isamapi:
      key: "{{ item.key }}"
      value: "{{ item.value }}"
      sensitive: "{{ item.sensitive }}"
  when: item is defined
  with_items: "{{ advanced_configurations }}"
  notify: Commit Changes