- name: Import File into runtime template files directory
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.aac.runtime_template.file.import_file
    isamapi:
      path        : "{{ item.path }}"
      name        : "{{ item.name }}"
      filename    : "{{ item.filename }}"
  with_items: "{{ import_aac_template_path_name_filename }}"
  when: import_aac_template_path_name_filename is defined
  notify:
  - Commit Changes
