- name: Deleting {{ delete_rsyslog_fowarder_sources_name }} from {{ delete_rsyslog_fowarder_sources_server }}:{{ delete_rsyslog_fowarder_sources_port }}
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: ibmsecurity.isam.base.remote_syslog.forwarder_sources.delete
    isamapi:
      server:   "{{ delete_rsyslog_fowarder_sources_server }}"
      port:     "{{ delete_rsyslog_fowarder_sources_port }}"
      protocol: "{{ delete_rsyslog_fowarder_sources_protocol }}"
      name:     "{{ delete_rsyslog_fowarder_sources_name }}"
  when: delete_rsyslog_fowarder_sources_server is defined and delete_rsyslog_fowarder_sources_port is defined and delete_rsyslog_fowarder_sources_protocol is defined and delete_rsyslog_fowarder_sources_name is defined
  notify: Commit Changes
