- name: download latest support file from appliance
  isam:
    appliance: "{{ inventory_hostname }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    lmi_port:  "{{ lmi_port }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action    : ibmsecurity.isam.base.support.download_latest
    isamapi:
      dir : "{{ download_latest_support_dir }}"
